kind: Deployment
apiVersion: apps/v1
metadata:
  name: devops
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: devops
  template:
    metadata:
      labels:
        app: debops
    spec:
      containers:
        - name: devops
          image: akelarmrf/webapp_devops
	  imagePullPolicy: Always
 	  ports:
	  - containerPort: 80
